version: '3.8'
services:
  # PHP/Apache container for REDCap
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redcap-php
    ports:
      - "8081:80"
    environment:
      MYSQL_HOST: mariadb
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      REDCAP_SALT: ${REDCAP_SALT}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
    depends_on:
      - mariadb
    volumes:
      - user_uploads:/var/user_uploads
      #- ${REDCAP_DIR}:/var/www/html
      # - ./girder_uploader_v1.0.0:/var/www/html/modules/girder_uploader_v1.0.0
    networks:
      - redcap-network
    restart: unless-stopped

  # MariaDB container for the database
  mariadb:
    image: mariadb:latest
    container_name: redcap-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER:-redcap_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-redcap_password}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-redcap_db}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - redcap-network
    command: ["mariadbd", "--max-allowed-packet=1G", "--optimizer_switch=rowid_filter=OFF"]
    restart: unless-stopped

volumes:
  mariadb_data:
  user_uploads: # Todo: mount on safe hard drive
networks:
  redcap-network:
    driver: bridge
