; RedCap specific PHP overrides
max_input_vars = 100000
upload_max_filesize = 32M
post_max_size = 32M
session.cookie_secure = On

; Increase memory limit for RedCap to handle larger datasets
memory_limit = 512M